---
- hosts: webservers
  become: yes
  tasks: 
  - name: i want to install tree
    apt:
      name: tree
      state: present
    when: ansible_os_family =="Debian"  
  
  - name: i want to install wget
    apt: 
      name: wget
      state: present
    when: ansible_os_family =="Debain"  

  - name: i want to install webserver apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family =="Debian"  

  - name: i want to install webserver on redhat
    yum:
      name: httpd
      state: present
    when: ansible_os_family =="RedHat"  

  - name: i want to start webserver on Redhat
    service:
      name: httpd
      state: started
    when: ansible_os_family =="RedHat"    

